### ISSUE TITLE
Moonracker error message

### ISSUE THREAD

**Issue by Seoman76** [cryd-s/Vyper_extended#14]
After auto update of moonracker.config a error message is shown in the dashboard

**Comment by cryd-s** [comment]
./scripts/install-moonraker.sh -r -f -c ~/klipper_config/moonraker.conf -l ~/klipper_logs/moonraker.log

**Comment by cryd-s** [comment]
This should solve your problem

**Comment by Seoman76** [comment]
Thx a lot for your support 

I tried it this morning but did not get it working 

I must beg your pardon but I am a rookie in case of computer 

Do I have to pass the commands in the main Menu v it a putty or change the directory to moonraker? 

Or but thus 3 commands in the moonraker.config

Beside that your project is great and very good for somebody not used to the stuff 

All went well with your Stepps and YouTube channel!

**Comment by cryd-s** [comment]
https://youtu.be/98NgjxiqhLw is this the problem?

**Comment by Seoman76** [comment]
That it

Thanks a lot 😀

BTW is it better to use English for contacting you or is it okay to use German ?

**Comment by cryd-s** [comment]
german is my main language but i can read english too - so take the the language u prefer
