### ISSUE TITLE
Can't start mainsail.

### ISSUE THREAD

**Issue by schwirzi** [cryd-s/Vyper_extended#32]
![20220228_150821](https://user-images.githubusercontent.com/99086908/156045474-0755c936-32d1-4cfd-8e88-5dba393cba05.jpg)
Hi manu, 
Ich habe gestern die sd Karte wie im Video vorbereitet. Aber unter der, in der fritzbox befindlichen IP Adresse war nur error 404 nichts zu finden.
Wenn ich nen Bildschirm ran hänge kommt das im oberen Bild stehende.
Danke für die Hilfe im voraus.

**Comment by thrukk** [comment]
Bitte neu installieren und user auf pi lassen. nur passwort ändern

**Comment by schwirzi** [comment]
Alles klar,  jetzt komm ich auf die Web Oberfläche. Danke für die schnelle
Hilfe

thrukk ***@***.***> schrieb am Mo., 28. Feb. 2022, 20:48:

**Comment by thrukk** [comment]
noch schneller gehts im discord
