### ISSUE TITLE
Fehler im Script in Zeile 22

### ISSUE THREAD

**Issue by LordMM74** [cryd-s/Vyper_extended#39]
Müsste es in Zeile 22 nicht

BACKUP_NET_DIR_CFG=/mnt/backup_fritz/klipper/backup$(date +'%Y-%m-%d')

anstatt

BACKUP_NET_DIR_CFG=/mnt/backupfritz/klipper/backup$(date +'%Y-%m-%d')

heißen?

**Comment by Anon0511** [comment]
Jap, das scheint mir richtig.

**Comment by Robnex** [comment]
Hallo,

Es wird im Laufe der nächsten 2 Woche eine Umstellung geben und das Script entfällt.

**Comment by Robnex** [comment]
Wird angepasst
