### ISSUE TITLE
= instead of :

### ISSUE THREAD

**Issue by bwnstck** [cryd-s/Vyper_extended#49]
https://github.com/cryd-s/Vyper_extended/blob/69503936ffc6809a3b33fa01ee68871131299f45/0_mods/Stealthburner_Mod/printer_stealthburner.cfg#L83

Already postet it here :P Idk which repo is used atm.

https://github.com/CrydTeam/Vyper_extended/issues/4

**Comment by Robnex** [comment]
Hello,

everything here is correct. Clipper uses "=" and not colons.

Variable = value
