### ISSUE TITLE
Change title of readme at  deprecated Projectclone

### ISSUE THREAD

**Issue by bwnstck** [cryd-s/Vyper_extended#50]
Iam still confused about the two repos with the same name and similar owner.

Could you please update either of those repos to be deprecated or why it exist? :) 
[
cryd-s/Vyper_extended](https://github.com/cryd-s/Vyper_extended) vs [CrydTeam/Vyper_extended](https://github.com/CrydTeam/Vyper_extended) 

There are also both links in the youtube description ...confusing (https://www.youtube.com/watch?v=9Y8h4HfBd18).

**Comment by Robnex** [comment]
Hello. 
You must have made a mistake. One is gitbook (which is on the crydteam github) and the other is cryd-s/github). All links to our github are correct.

The repository that is maintained is the cryd-s/github
